In [2]:
import numpy as np

import pandas as pd

import matplotlib.plyplot as plt

%matplotlib inliner


ModuleNotFoundError: No module named 'matplotlib.plyplot'

In [3]:
# mean:
m= np.random.randint(7,10,20)
print(m)

[9 9 9 9 8 9 9 8 8 9 8 8 9 7 9 7 8 9 8 9]


In [4]:
np.mean(m)

8.45

In [5]:
# median :
np.median(m)

9.0

In [6]:
# mode :
from statistics import mode
mode(m)

9

In [7]:
# Population and sample :
pop = np.random.randint(10,20,100)
pop

array([13, 15, 17, 16, 12, 15, 17, 11, 19, 15, 15, 19, 13, 17, 11, 19, 16,
       13, 16, 14, 17, 15, 10, 12, 18, 19, 13, 11, 13, 11, 15, 15, 11, 12,
       11, 12, 10, 12, 19, 19, 12, 13, 17, 10, 14, 19, 15, 17, 10, 15, 12,
       13, 13, 13, 19, 16, 18, 18, 13, 13, 17, 16, 19, 15, 11, 15, 13, 15,
       19, 18, 12, 12, 13, 10, 11, 15, 12, 16, 17, 18, 13, 17, 13, 10, 14,
       19, 18, 17, 13, 19, 18, 17, 11, 19, 10, 16, 18, 16, 16, 12])

In [8]:
np.mean(pop)

14.68

In [9]:
np.median(pop)

15.0

In [10]:
mode(pop)

13

In [11]:
# sample :
sample = np.random.choice(pop,10)
sample

array([10, 19, 17, 11, 19, 16, 18, 13, 11, 13])

In [12]:
# mean
np.mean(sample)

14.7

In [13]:
# median 
np.median(sample)

14.5

In [14]:
# mode
mode(sample)

19

In [15]:
dir(mode)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [16]:
df = pd.read_csv("C:\\Users\\vamsi\\Downloads\\CarPrice_Assignment.csv")
df

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [17]:
list_1=list(df.price)
print(list_1)

[13495.0, 16500.0, 16500.0, 13950.0, 17450.0, 15250.0, 17710.0, 18920.0, 23875.0, 17859.167, 16430.0, 16925.0, 20970.0, 21105.0, 24565.0, 30760.0, 41315.0, 36880.0, 5151.0, 6295.0, 6575.0, 5572.0, 6377.0, 7957.0, 6229.0, 6692.0, 7609.0, 8558.0, 8921.0, 12964.0, 6479.0, 6855.0, 5399.0, 6529.0, 7129.0, 7295.0, 7295.0, 7895.0, 9095.0, 8845.0, 10295.0, 12945.0, 10345.0, 6785.0, 8916.5, 8916.5, 11048.0, 32250.0, 35550.0, 36000.0, 5195.0, 6095.0, 6795.0, 6695.0, 7395.0, 10945.0, 11845.0, 13645.0, 15645.0, 8845.0, 8495.0, 10595.0, 10245.0, 10795.0, 11245.0, 18280.0, 18344.0, 25552.0, 28248.0, 28176.0, 31600.0, 34184.0, 35056.0, 40960.0, 45400.0, 16503.0, 5389.0, 6189.0, 6669.0, 7689.0, 9959.0, 8499.0, 12629.0, 14869.0, 14489.0, 6989.0, 8189.0, 9279.0, 9279.0, 5499.0, 7099.0, 6649.0, 6849.0, 7349.0, 7299.0, 7799.0, 7499.0, 7999.0, 8249.0, 8949.0, 9549.0, 13499.0, 14399.0, 13499.0, 17199.0, 19699.0, 18399.0, 11900.0, 13200.0, 12440.0, 13860.0, 15580.0, 16900.0, 16695.0, 17075.0, 16630.0, 17950.

In [18]:
# mean :

m =np.mean(list_1)
m



13276.710570731706

In [19]:
# median :
m=np.median(list_1)
m

10295.0

In [20]:
# mode :

mode(list_1)

16500.0

In [21]:
# var :
m=np.var(list_1)
m

63510435.91216187

In [22]:
# Standard Deviation :

m=np.std(list_1)
m


7969.34350572002